# -*- coding: utf-8 -*-
"""Task 3.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXmn-BzlZ-D34dfkFcCFbE2GlmgTqdxO
"""

import pandas as pd

df = pd.read_excel('/content/Student Feedback.xlsx')

display(df.head())
display(df.info())

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the average response for each question (excluding 'Student ID')
average_responses = df.drop('Student ID', axis=1).mean()

# Create a bar chart
plt.figure(figsize=(12, 6))
sns.barplot(x=average_responses.index, y=average_responses.values)
plt.xticks(rotation=90)
plt.title('Average Response for Each Question')
plt.ylabel('Average Response')
plt.xlabel('Question')
plt.tight_layout()
plt.show()

import pandas as pd

df = pd.read_excel('/content/Student Feedback.xlsx')

"""## Summary:

### Data Analysis Key Findings

*   The data from the "Student Feedback.xlsx" file was successfully loaded into a pandas DataFrame.
*   The average responses for each question were calculated and visualized in a bar chart.
*   The average responses are as follows:
    *   Well versed with the subject: {{average_responses['Well versed with the subject']:.2f}}
    *   Explains concepts in an understandable way: {{average_responses['Explains concepts in an understandable way']:.2f}}
    *   Use of presentations: {{average_responses['Use of presentations']:.2f}}
    *   Degree of difficulty of assignments: {{average_responses['Degree of difficulty of assignments']:.2f}}
    *   Solves doubts willingly: {{average_responses['Solves doubts willingly']:.2f}}
    *   Structuring of the course: {{average_responses['Structuring of the course']:.2f}}
    *   Provides support for students going above and beyond: {{average_responses['Provides support for students going above and beyond']:.2f}}
    *   Course recommendation based on relevance: {{average_responses['Course recommendation based on relevance']:.2f}}

*   Due to the absence of the "Feedback" column, the text preprocessing and sentiment analysis steps could not be performed.

### Insights or Next Steps

*   Verify the correct Excel file path and ensure the "Feedback" column exists in the source data if sentiment analysis is desired.
*   Consider creating a dashboard to interactively explore these average responses and potentially other aspects of the data if available.
"""